version: '3'

services:
  
  cms_nginx:
    volumes:
      - ./mautic/mautic_data:/var/www/html
    depends_on:
      - mautic

  mauticdb:
    image: percona/percona-server:5.7
    container_name: mauticdb
    volumes:
      - ./mautic/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    
  mautic:
    image: mautic/mautic:v4
    container_name: mautic
    links:
      - mauticdb:mysql
    depends_on:
      - mauticdb
    ports:
      - 8080:80
    volumes:
      - ./mautic/mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MYSQL_PORT_3306_TCP=${MYSQL_PORT_3306_TCP}
      - MAUTIC_DB_USER=${MAUTIC_DB_USER}
      - MAUTIC_DB_PASSWORD=${MAUTIC_DB_PASSWORD}
      - MAUTIC_DB_NAME=${MAUTIC_DB_NAME}
      - MAUTIC_RUN_CRON_JOBS=${MAUTIC_RUN_CRON_JOBS}
      # - MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0